812: implement hotfix workflow

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,6 +20,39 @@ commands:
                     git config user.email "62934656+deliverino[bot]@users.noreply.github.com"
                     git remote set-url origin "https://x-access-token:${DELIVERINO_ACCESS_TOKEN}@github.com/digitalfabrik/lunes-cms.git"
                 name: Configure git to commit & push as Deliverino app
+    notify:
+        description: Send a notification (to Mattermost) at the end of a job, based on success or failure. Must be the last step in a job.
+        parameters:
+            allow_all_branches:
+                default: false
+                type: boolean
+            channel:
+                default: lunes-notifications
+                type: string
+            failure_mentions:
+                default: ""
+                type: string
+            success_mentions:
+                default: ""
+                type: string
+            success_message:
+                default: ""
+                type: string
+        steps:
+            - run:
+                command: |
+                    echo 'export MM_MESSAGE=":fire: [${CIRCLE_JOB}](${CIRCLE_BUILD_URL}) failed on branch ${CIRCLE_BRANCH}! :fire: << parameters.failure_mentions >>"' >> $BASH_ENV
+                name: Mattermost - Prepare failure message
+                when: on_fail
+            - run:
+                command: echo 'export MM_MESSAGE="<< parameters.success_message >>"' >> $BASH_ENV
+                name: Mattermost - Prepare success message
+                when: on_success
+            - run:
+                command: scripts/notify-mattermost << parameters.channel >> << parameters.allow_all_branches >>
+                name: Mattermost Status Alert
+                when: always
+                working_directory: ~/project
 executors:
     python:
         docker:
@@ -151,11 +184,13 @@ jobs:
                 name: Calculate next version
             - run:
                 command: |
+                    HOTFIX_FLAG=$([[ "${CIRCLE_BRANCH}" == hotfix* ]] && echo "--hotfix" || true)
                     npx --no app-toolbelt v0 release bump-to "${NEW_VERSION}" 0 \
                       --private-key "${DELIVERINO_PRIVATE_KEY}" \
                       --owner "${CIRCLE_PROJECT_USERNAME}" \
                       --repo "${CIRCLE_PROJECT_REPONAME}" \
-                      --branch "${CIRCLE_BRANCH}"
+                      --branch "${CIRCLE_BRANCH}" \
+                      ${HOTFIX_FLAG}
                 name: Bump git version
     check-translations:
         executor: python
@@ -203,12 +238,13 @@ jobs:
                 name: Install app-toolbelt
             - run:
                 command: |
+                    HOTFIX_FLAG=$([[ "${CIRCLE_BRANCH}" == hotfix* ]] && echo "--hotfix --branch ${CIRCLE_BRANCH}" || true)
                     NEW_VERSION=$(jq -r .versionName version.json)
                     RELEASE=$(npx --no app-toolbelt v0 release create all "${NEW_VERSION}" \
                       --private-key "${DELIVERINO_PRIVATE_KEY}" \
                       --owner "${CIRCLE_PROJECT_USERNAME}" \
                       --repo "${CIRCLE_PROJECT_REPONAME}" \
-                      --branch main)
+                      ${HOTFIX_FLAG})
                     echo "export RELEASE_ID=$(echo ${RELEASE} | jq .id)" >> ${BASH_ENV}
                     echo "export RELEASE_NOTES=$(echo ${RELEASE} | jq .releaseNotes)" >> ${BASH_ENV}
                 name: Create GitHub pre-release
